# Generated by Django 3.1.2 on 2020-10-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decrittor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Detector', models.CharField(max_length=30)),
                ('descrizion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('EarthLimbAngle', models.FloatField()),
                ('Name', models.CharField(max_length=30)),
                ('Detector', models.CharField(max_length=30)),
            ],
        ),
    ]
